config/routes.rb
Pkwmanager::Application.routes.draw do
  resources :manufactors

  resources :cars

  root 'cars#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :manufactors
end

app/models/manufactor.rb
class Manufactor < ActiveRecord::Base
  belongs_to :car
end

app/models/pkw.rb
class Car < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new

  end

  # GET /cars/1/edit
  def edit
    @manufactor =Manufactor.find(:all, :order => 'manufactor')
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'car was successfully created.' }
        format.json { render action: 'show', status: :created, location: @car }
      else
        format.html { render action: 'new' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:manufactor_id,:marque, :model, :milage, :MOT)
    end
end

app/controllers/manufactors_controller.rb
class ManufactorsController < ApplicationController
  before_action :set_manufactor, only: [:show, :edit, :update, :destroy]

  # GET /manufactors
  # GET /manufactors.json
  def index
    @manufactors = Manufactor.all
  end

  # GET /manufactors/1
  # GET /manufactors/1.json
  def show
  end

  # GET /manufactors/new
  def new
    @manufactor = Manufactor.new
  end

  # GET /manufactors/1/edit
  def edit
  end

  # POST /manufactors
  # POST /manufactors.json
  def create
    @manufactor = Manufactor.new(manufactor_params)

    respond_to do |format|
      if @manufactor.save
        format.html { redirect_to @manufactor, notice: 'Manufactor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @manufactor }
      else
        format.html { render action: 'new' }
        format.json { render json: @manufactor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manufactors/1
  # PATCH/PUT /manufactors/1.json
  def update
    respond_to do |format|
      if @manufactor.update(manufactor_params)
        format.html { redirect_to @manufactor, notice: 'Manufactor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @manufactor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufactors/1
  # DELETE /manufactors/1.json
  def destroy
    @manufactor.destroy
    respond_to do |format|
      format.html { redirect_to manufactors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manufactor
      @manufactor = Manufactor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manufactor_params
      params.require(:manufactor).permit(:manufactor)
    end
end

app/controllers/pkws_controller.rb
class carsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @car = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'car was successfully created.' }
        format.json { render action: 'show', status: :created, location: @car }
      else
        format.html { render action: 'new' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:marke, :modell, :kilometerstand, :tüv)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manufactors_helper.rb
module ManufactorsHelper
end

app/helpers/pkws_helper.rb
module PkwsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%=f.label :manufactor %><br>
     <%= f.select :manufactor_id,
     Manufactor.all.map { |d| [d.manufactor,d.id]},
     prompt: "Please select" %>
  </div>

  <div class="field">
    <%= f.label :marque %><br>
    <%= f.text_field :marque %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :milage %><br>
    <%= f.number_field :milage %>
  </div>
  <div class="field">
    <%= f.label :MOT %><br>
    <%= f.check_box :MOT %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>
<hr>
<%= render 'form' %>

<%= link_to 'Show', @car ,:class=>"btn-sm btn-primary"%> |
<%= link_to 'Back', car_path,:class=>"btn-sm btn-primary" %>

app/views/cars/index.html.erb
<h1> <%= image_tag("mcqueen.jpg",:size => "100x64") %>Listing Cars</h1>
<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Manufactor</th>
      <th>Marque</th>
      <th>Model</th>
      <th>Milage</th>
      <th>MOT</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>

    <% @cars.each do |car| %>

      <tr>
        <td><%= car.manufactor_id %></td>
        <td><%= car.marque %></td>
        <td><%= car.model %></td>
        <td><%= car.milage %></td>
        <td><%= car.MOT %></td>
        <td><%= link_to 'Show', car,:class=>"btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_car_path(car),:class=>"btn btn-primary" %></td>
        <td><%= link_to 'Destroy', car,:class=>"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

    <%end%>
  </div>
  </tbody>
</table>

<br>

<%= link_to 'New car', new_car_path,:class=>"btn btn-success" %>

app/views/cars/new.html.erb
<h1>New Car</h1>
<hr>
<%= render 'form' %>

<%= link_to 'Back', cars_path ,:class=>"btn-sm btn-primary"%>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Show My Car </h2>
<p>
  <strong>Manufactor:</strong>
  <%= @car.manufactor_id %>
</p>

<p>
  <strong>Marque:</strong>
  <%= @car.marque %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Milage:</strong>
  <%= @car.milage %>
</p>

<p>
  <strong>MOT:</strong>
  <%= @car.MOT %>
</p>

<%= link_to 'Edit', edit_car_path(@car),:class=>"btn-sm btn-primary" %> |
<%= link_to 'Back', cars_path,:class=>"btn-sm btn-primary"  %>

app/views/layouts/application.html.erb
<head>
  <title>CarsManager</title>
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="http://twitter.github.io/bootstrap/assets/js/bootstrap-transition.js"></script>
    <script type="text/javascript" src="http://twitter.github.io/bootstrap/assets/js/bootstrap-collapse.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
      <div class="container">
        <div class="navbar navbar-fixed-top">
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CarsManager</a>
</div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

            <li><%= link_to "Cars", :controller => :cars, :action => :index %></a></li>
            <li><%= link_to "Manufactors", :controller => :manufactors, :action => :index %></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container-fluid">
<div class="row-fluid">
      <div class="span10"><%= yield %></div>
    </div>
  </div>
</body>

app/views/manufactors/_form.html.erb
<%= form_for(@manufactor) do |f| %>
  <% if @manufactor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manufactor.errors.count, "error") %> prohibited this manufactor from being saved:</h2>

      <ul>
      <% @manufactor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :manufactor %><br>
    <%= f.text_field :manufactor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manufactors/edit.html.erb
<h1>Editing manufactor</h1>

<%= render 'form' %>

<%= link_to 'Show', @manufactor ,:class=>"btn btn-primary"%> |
<%= link_to 'Back', manufactors_path,:class=>"btn btn-primary" %>

app/views/manufactors/index.html.erb
<h1>Listing Manufactors</h1>

<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Manufactor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @manufactors.each do |manufactor| %>
      <tr>
        <td><%= manufactor.manufactor %></td>
        <td><%= link_to 'Show', manufactor ,:class=>"btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_manufactor_path(manufactor),:class=>"btn btn-primary" %></td>
        <td><%= link_to 'Destroy', manufactor,:class=>"btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </div>
  </tbody>
</table>

<br>

<%= link_to 'New Manufactor', new_manufactor_path,:class=>"btn btn-success" %>

app/views/manufactors/new.html.erb
<h1>New manufactor</h1>

<%= render 'form' %>

<%= link_to 'Back', manufactors_path,:class=>"btn btn-primary" %>

app/views/manufactors/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Show My Manufactors </h2>
<p>
  <strong>Manufactor:</strong>
  <%= @manufactor.manufactor %>
</p>

<%= link_to 'Edit', edit_manufactor_path(@manufactor),:class=>"btn-sm btn-primary" %> |
<%= link_to 'Back', manufactors_path,:class=>"btn-sm btn-primary" %>

app/views/pkws/_form.html.erb
<%= form_for(@pkw) do |f| %>
  <% if @pkw.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pkw.errors.count, "error") %> prohibited this pkw from being saved:</h2>

      <ul>
      <% @pkw.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marque %><br>
    <%= f.text_field :marque %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :milage %><br>
    <%= f.number_field :milage %>
  </div>
  <div class="field">
    <%= f.label :MOT %><br>
    <%= f.check_box :MOT %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pkws/index.html.erb
<h1>Listing cars</h1>

<table>
  <thead>
    <tr>
      <th>Marque</th>
      <th>Model</th>
      <th>Milage</th>
      <th>MOT</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.marke %></td>
        <td><%= car.modell %></td>
        <td><%= car.kilometerstand %></td>
        <td><%= car.tüv %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New car', new_car_path %>

app/views/pkws/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', pkws_path %>

app/views/pkws/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marque:</strong>
  <%= @car.marque %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Milage:</strong>
  <%= @car.milage %>
</p>

<p>
  <strong>MOT:</strong>
  <%= @car.milage %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>